# Generated by Django 5.1.1 on 2024-12-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1_matches', to='api.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_matches', to='api.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player3_matches', to='api.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player4_matches', to='api.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner1_matches', to='api.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner2_matches', to='api.player'),
        ),
    ]
