# Generated by Django 5.1.1 on 2024-12-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_match_player1_alter_match_player2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['created_at']},
        ),
    ]
