# Generated by Django 5.1.1 on 2024-12-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_match_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['created_at']},
        ),
    ]
