# Generated by Django 5.1.1 on 2024-10-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_match_player1_score_alter_match_player2_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='match',
            name='round_of',
        ),
        migrations.AddField(
            model_name='match',
            name='round_stage',
            field=models.CharField(blank=True, choices=[('SF', 'Semifinals'), ('F', 'Final')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_matches', to='players.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1_matches', to='players.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_matches', to='players.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='players.tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='players.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='players.player'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('player', 'friend'), name='unique_friend_for_player'),
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipant',
            constraint=models.UniqueConstraint(fields=('tournament', 'player'), name='unique_tournament_participant'),
        ),
    ]
