# Generated by Django 5.1.1 on 2024-10-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='avatars/'),
        ),
    ]
