# Generated by Django 5.1.1 on 2024-10-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
