# Generated by Django 5.1.1 on 2024-10-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_created_at_player_updated_at_tournament_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
